### ISSUE TITLE
Shadow not showing

### ISSUE THREAD

**Issue by ahmadayikrifai** [beigirad/ZigzagView#11]
Shadow on zigzag view not showing

**Comment by beigirad** [comment]
@ahmadayikrifai 
Could you give more information about the environment (device, Android API level,...)?

**Comment by MerlijnClaeys** [comment]
I got the same issue since using version 1.0.7 and higher, shadows still work on 1.0.5.

using android 8 device.

**Comment by MerlijnClaeys** [comment]
had a look in the source code and found the issue i believe.

When converting to Kotlin this line of code was dropped from the constructor of the ZigZagView
 setLayerType(LAYER_TYPE_SOFTWARE, null)

I added this back to the init {} block and shadows are now working again

**Comment by beigirad** [comment]
@MerlijnClaeys Thanks for your contribution. try `1.2.1`.

**Comment by MerlijnClaeys** [comment]
yes, tested and works fine now :)
