### ISSUE TITLE
adding zigzag on top

### ISSUE THREAD

**Issue by atiruz** [beigirad/ZigzagView#3]
how can put zig zag on top the ZigzagView?
I known that need modify drawZigzag function, but I can't without break the bottom.

**Comment by atiruz** [comment]
I replied the code with some adjustments at the end of the function

    private void drawZigzag() {
        float left = rectZigzag.left;
        float right = rectZigzag.right;
        float top = rectZigzag.top;
        float bottom = rectZigzag.bottom;
        int width = (int) (right - left);

        pathZigzag.moveTo(right, bottom);
        pathZigzag.lineTo(right, top);
        pathZigzag.lineTo(left, top);
        pathZigzag.lineTo(left, bottom);

        int h = zigzagHeight;
        int seed = 2 * h;
        int count = width / seed;
        int diff = width - (seed * count);
        int sideDiff = diff / 2;

        float x = (float) (seed / 2);
        float upHeight = bottom - h;
        for (int i = 0; i < count; i++) {
            int startSeed = (i * seed) + sideDiff + (int) left;
            int endSeed = startSeed + seed;

            if (i == 0) {
                startSeed = (int) left + sideDiff;
            } else if (i == count - 1) {
                endSeed = endSeed + sideDiff;
            }

            this.pathZigzag.lineTo(startSeed + x, upHeight);
            this.pathZigzag.lineTo(endSeed, bottom);
        }

        // TOP ZIG ZAG
        pathZigzag.moveTo(left, top);
        upHeight = top - h;
        for (int i = 0; i < count; i++) {
            int startSeed = (i * seed) + sideDiff + (int) left;
            int endSeed = startSeed + seed;

            if (i == 0) {
                startSeed = (int) left + sideDiff;
            } else if (i == count - 1) {
                endSeed = endSeed + sideDiff;
            }

            this.pathZigzag.lineTo(startSeed + x, upHeight);
            this.pathZigzag.lineTo(endSeed, top);
        }
    }

This change could be parameterized in the configuration of the ZigzagView :)

**Comment by beigirad** [comment]
Hello Atiruz,
I added draw TopZigzag feature in [v1.0.5](https://github.com/beigirad/ZigzagView/releases/tag/1.0.5)

Now you can use new attributes in this version.
