### ISSUE TITLE
how to add corner radius?

### ISSUE THREAD

**Issue by anggit97** [beigirad/ZigzagView#5]

**Comment by beigirad** [comment]
Corner radius for where?
for all small edges or for root layout?

**Comment by anggit97** [comment]
@beigirad I want to add radius to top left and right only. How to do that?

**Comment by beigirad** [comment]
Could you show me an image/scratch/shot from what do you want?

**Comment by anggit97** [comment]
https://imgur.com/a/qjjiLYh

I want to make the radius only on top left and right only in the image attach above

**Comment by beigirad** [comment]
It's not require adding corner radius for ZigZagView, and you can add the ZigZagView into a CardView.

Your shot seems used cardView too.

**Comment by anggit97** [comment]
Right now I'm using cardview to handle that one. Maybe it can better if there feature to add corner radius from xml😊

**Comment by beigirad** [comment]
Thanks for your suggest, but the shadow of ZigZagView is not standard like CardView shadow. and not suitable for to use instead of CardView.
